import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "27Notes",
  description: "Generated by create next app",
  icons : {
    icon : ['./27Notes.png']
  } 
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" href="" />
        </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
